raylib/Web.toml

The `link-args` of `samples/Web.toml` are enough, since the ones added from `raylib/Web.toml` are duplicated and unnecessary. Since link args are only used for the final output and all link args from every Web.toml of every crate are used, we don't need this duplicity.
Also, by not forcing any link args on raylib, we can let users specify the flags they need. For instance, with `fastcomp-latest` the `ASYNCIFY` option is not supported anymore:
`= note: shared:ERROR: ASYNCIFY has been removed from fastcomp. There is a new implementation which can be used in the upstream wasm backend.`

Remove link args from raylib when building with cargo-web

---

raylib/src/core/texture.rs

`Texture2D.height()` return the width strangely but `Texture2D.height` is unaffected.

Fixed Texture2D.height() calls

---

raylib/src/core/color.rs

Implemented `From<&str>` for colors.
Once const functions are stable in Rust, this could be turned into a compile-time macro, so one can initialize constant values in their color schemes in a sound and pleasant manner.

Produce color from hex RGB strings

---

raylib/src/core/math.rs

The current implementation returns a "normalized" vector as the vector where each component is the x component divided by the length of the vector.

Fix to normalized() for Vector3

---

raylib-test/src/models.rs
raylib/src/core/models.rs

This check doesn't allow for meshes generated using the gen_mesh methods like gen_mesh_cube.
It should fix issue #57 
let me know if I should do something else with this... I'd be happy to improve the PR in any way necessary

remove check for bones and poses in load_model_from_mesh

---

raylib-sys/build.rs

This PR fixes #66, #73, and probably #75.
Since cmake will produce `libraylib.a` when cross-compiling, the `build.rs` will now handle it correctly and not fail.
I also made the "is windows" check reference the compiler triple so that the library can be cross-compiled using cargo's `--target` option no matter the host OS

Fix Windows cross-compile issues from Linux

---

raylib/src/core/shaders.rs
raylib/src/core/window.rs

I'm working with this library, trying to get it running on the Pi. On ARM systems, Rust uses`u8` for `char *` rather than `i8`. The most portable thing to do here would be to cast as `std::os::raw::c_char` instead of `i8` (Fixes #10).

Use proper pointer types for architecture (Fixes #10)

---

raylib/Cargo.toml
raylib/src/core/math.rs

I have been in need of a way to use some structs like `Vector3` and `Quaternion` with [`serde`](https://serde.rs/). I figured I'd give a shot at turning this into a PR.
This change adds a new feature called `with_serde` that will turn every struct in `raylib::core::math` into something `serde` can understand.
I am quite new to rust, so I don't expect my implementation is perfect. Please give me feedback on my work.

Add optional serde support to math-related structs

---

raylib/Cargo.toml
raylib/src/core/math.rs
raylib/src/lib.rs

I like to use the [nalgebra](https://nalgebra.org/) library for my linear algebra needs. This PR just adds an optional feature to this library (`nalgebra_interop`) that implements `Into` and `From` traits between the raylib vector types and the nalgebra ones.

Add optional interop with nalgebra

---

raylib/src/core/texture.rs

Added a wrapper for LoadImageFromMemory. This allows "bundling" data in the binary itself via the rust include_bytes! macro.

Added binding for LoadImageFromMemory

---

raylib/src/core/math.rs

- Add `lerp()` function for single `f32` value.
- Add `lerp()` function for `Vector2`.
- Add `clamp()` function for `Vector2`, `Vector3`, and `Vector4` / `Quaternion`.
I simply thought that these functions would be nice to have within the library.

Convenience functions for vectors

---

README.md

This took me way too long to figure it.
I only managed to find it thanks to a [closed issue](https://github.com/deltaphc/raylib-rs/issues/89).
I think this step should be documented.
Please let me know if there's a better place for it, couldn't find a more appropriate place to put it.

Add submodule documentation

---

raylib/Cargo.toml

I ran into a confusing scenario when upgrading to 3.7 from 3.5 which seems to be caused by the current versioning scheme not following [semver](https://semver.org/). [More details here](https://users.rust-lang.org/t/is-cargo-intended-to-act-this-way-or-it-a-bug/70237/5).
Now, having the version number intuitively matching the C Raylib's version number is worth something, and my scenario seems to be rare, so I'm not necessarily suggesting that the version numbering should be changed. But as I understand it, if the `raylib` crate specifies the exact version of `raylib-sys` to use, then at least part of the confusing situation would have been avoided. And pinning the raylib version in my `Cargo.toml` would have worked, without needing to specify `raylib-sys` explicitly. This seems like an …

Pin to the exact version of raylib-sys

---

raylib/src/core/math.rs

- removed `zero()` and `one()` functions
- added constant definitions for zero and one
These functions can be swapped out for constant definitions since they always return the same value.
Alternatively, these can also be changed to const/inline functions.

Vector2 Constants

---

raylib/src/core/color.rs
raylib/src/core/window.rs

Add `#[cfg(feature = "serde")] use serde::{Serialize, Deserialize};` to color.rs and window.rs to fix serde support

Fix serde support for color.rs and window.rs

---

samples/3d_camera_first_person.rs

`gen_range()` now requires a single parameter `Range` rather than two ints

Updated example as per API change in `rand` crate

---

raylib-sys/build.rs

In accordance with https://github.com/deltaphc/raylib-rs/issues/11

Add missing linked libraries for RPI support

---

README.md
raylib-sys/Cargo.toml
raylib-sys/build.rs

Adds support for wayland (did not work without linking to local glfw) for https://github.com/deltaphc/raylib-rs/issues/119
Adds ability to force OpenGL version to 3.3, 2.1, or ES 2.0 (I couldn't get 1.1 working if anyone wanted to take a stab at that) for https://github.com/deltaphc/raylib-rs/issues/90 and https://github.com/deltaphc/raylib-rs/issues/122
Also changed the README to accommodate for changes

Wayland Support + Forcing OpenGL Version

---

README.md
raylib/Cargo.toml
raylib/src/core/input.rs

This enables setting the wayland feature in your Cargo.toml file:
```
[dependencies]
raylib = { ..., features = ["wayland"] }
```
Also it fixes the latest build issue ( https://github.com/deltaphc/raylib-rs/actions/runs/2547187213 )

Expose wayland feature and fix u32 conversion issue

---

raylib/src/core/audio.rs

This PR just adds a binding for the raylib function `LoadWaveFromMemory` called `Wave::load_wave_from_mem()`.

Add binding for `LoadWaveFromMemory()`

---

raylib/src/core/texture.rs

After having a long time not understanding that the "." in the ".png" was key, I thought I would put a slight hint to future devs using this function.

added comment explaining filetype variable of load_image_from_mem

---

README.md

I changed my username a couple of months ago to be more consistent with other platforms I'm on

update fork link in readme

---

raylib-sys/build.rs
raylib/src/core/math.rs
raylib/src/core/text.rs
raylib/src/core/texture.rs

A simple but nice to have change to Image::load_image_from_mem:
- Pass the data buffer in as a slice instead of a Vec. We don't really need the vector's functionality here, so we shouldn't force the user to create one (also mentioned in #106).
- Remove the size parameter, we can get the size from the slice/vector.
Points of consideration:
- Use `try_into` when converting the buffer's size into a i32. Using `try_into().unwrap()` would panic when the buffers size exceeds i32's range. That doesn't sound very likely, but I think it's better to have the crash happen here, rather than leave raylib to deal with a negative size.
Note. I'm new to Rust as a language so I'm not sure if this is 100% right, feel free to yell at me if this code makes no sense :)

simplify load_image_from_mem function

---

raylib/src/core/math.rs

This change reflects the fix done in https://github.com/raysan5/raylib/issues/1651. I found from_euler was not behaving as expected when changing yaw, pitch, and roll for a 3d camera. When I provide values in the the same order now used in raymath (pitch, yaw, roll), rotation behavior is as expected.

Updates from_euler parameter names to match raymath's QuaternionFromEuler
